name: 缺陷清单
description: 帮助我们解决存在的问题
labels: [bug]
body:
  - type: markdown
    id: preface
    attributes:
      value: |
        感谢你花时间填写此错误报告！在开始之前，我们非常推荐阅读一遍[《开源最佳实践》](https://github.com/LinuxSuRen/open-source-best-practice)，这会在很大程度上提高我们彼此的效率。
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: "是什么版本出现了此问题？"
  - type: input
    id: halo-version
    validations:
      required: true
    attributes:
      label: "Halo 版本"
  - type: dropdown
    id: platform
    validations:
      required: true
    attributes:
      label: "平台"
      options:
        - 桌面端
        - 移动端
  - type: input
    id: os
    attributes:
      label: "操作系统"
  - type: input
    id: web-browser
    attributes:
      label: "浏览器"
  - type: input
    id: site-url
    attributes:
      label: "在线站点地址"
      description: "请提供你的站点地址，如果可以的话，这可能会帮助我们更好的定位问题。"
      placeholder: "ex. bbchin.com"
    validations:
      required: false
  - type: markdown
    id: details
    attributes:
      value: "## 详细信息"
  - type: textarea
    id: what-happened
    validations:
      required: true
    attributes:
      label: "描述缺陷"
      description: "请简洁而清晰的描述一下这个缺陷。"
  - type: textarea
    id: reproduction
    attributes:
      label: "如何复现"
  - type: textarea
    id: desired-result
    attributes:
      label: "期望结果"
      description: "简洁而清晰的描述一下你最终期望的结果。"
  - type: textarea
    id: additional-information
    attributes:
      label: "附加信息"
      description: "如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。"
