---
name: 缺陷清单
about: 帮助我们解决存在的问题
title: ""
labels: bug
assignees: ""
---

**描述缺陷**

请简洁而清晰的描述一下这个缺陷。

**如何复现**

复现步骤如下:

1. 打开 "xxx"
2. 点击 "xxx"
3. 滚动到 "xxx"
4. 发生错误

**期望结果**

简洁而清晰的描述一下你最终期望的结果。

**截图**

如有需要，可以附上一些截图。

**PC 端 (请提供以下信息):**

- Halo 版本：[e.g. 1.4.11]
- 操作系统：[e.g. iOS]
- 浏览器：[e.g. chrome, safari]
- 版本：[e.g. 22]

**移动端 (请提供以下信息):**

- Halo 版本：[e.g. 1.4.11]
- 设备型号：[e.g. iPhone6]
- 操作系统：[e.g. iOS8.1]
- 浏览器：[e.g. stock browser, safari]
- 版本：[e.g. 22]

**额外信息**

可以添加一些额外的对我们处理这个问题有帮助的信息。
